config/routes.rb
Rails.application.routes.draw do

  get '/game' => 'longest_word#game', as: 'game'

  get '/score' => 'longest_word#score', as: 'score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_word_controller.rb
require 'open-uri'
require 'json'

class LongestWordController < ApplicationController

  def game
    @grid = generate_grid(rand(10..26))
    @start_time = Time.now
  end

  def score
    @word = params[:word]
    @translated_word = get_translation(@word)
    @grid = params[:grid]
    @start_time = Time.parse(params[:start_time])
    @time = (Time.now - @start_time)/1000
    @score = score_and_message(@word, @translated_word, @grid, @time)
    @score[0] = @score[0].round(1)
  end

  private

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end


  def included?(guess, grid)
    guess.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time])

    result
  end

  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase.split, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def get_translation(word)
    api_key = "YOUR_SYSTRAN_API_KEY"
    begin
      response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
      json = JSON.parse(response.read.to_s)
      if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
        return json['outputs'][0]['output']
      end
    rescue
      if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
        return word
      else
        return nil
      end
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/longest_word_helper.rb
module LongestWordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longest_word/game.html.erb
<h1>******** Welcome to the longest word-game !********</h1>
<p><%= @grid %></p>
<form action="/score">
  <label for="question">What's your best shot?</label>
  <input type="text" id="question" name="word" placeholder="Your proposition">
  <input type="hidden" name="grid" value=<%= @grid.join %>>
  <input type="hidden" name="start_time" value=<%= @start_time %>>
  <input type="submit" value="Submit">
</form>

app/views/longest_word/score.html.erb
<p>******** Now your results ********</p>
<p>Your word: <%= @word %></p>
<p>Time Taken to answer: <%= @time.to_i %> s</p>
<p>Your score: <%= @score[0] %> pts</p>
<p>Message: <%= @score[1] %></p>

<%= link_to "Replay", game_path %>